### PR TITLE
Choose to force trailing slash—or not

### PR DESCRIPTION
**Pull request by thomasjbradley**
I wanted the ability to force no trailing slash instead of forcing a trailing slash.

There is now a second argument for choosing to have a slash or not, like:

``` js
// Force no trailing slash
app.use(slash(301, false));
```

### CODE REVIEW

**Comment by ericf** [comment]
Thanks for this! I think I want to approach this differently though. It seems like it can be automatic since this middleware is suppose to come after `app.router`; if a request has a slash, then it will remove it and see if a route matches, and visa versa.

Do you think that sort of automatic approach will work for you?

**Comment by thomasjbradley** [comment]
Yeah, automatic would work really well.

**Comment by ericf** [comment]
@thomasjbradley Let me know what you think of the solution I provided for this feature in #2.

**Comment by thomasjbradley** [comment]
@ericf That solution looks good to me.

**Comment by ericf** [comment]
@thomasjbradley okay cool. I'm going to close this pull request then, in favor of the automatic approach. I'll ping you once it's merged and published to npm.

**Comment by ericf** [comment]
@thomasjbradley I've published these changes to npm.

**Comment by thomasjbradley** [comment]
@ericf Cool; thanks!

**Pull request closed without merging**
